# Generated by Django 5.2.17 on 2026-09-09 14:52

import InvenTree.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('company', '0081_remove_company_notes_remove_manufacturerpart_notes_and_more'),
        ('part', '0154_remove_part_notes'),
        ('stock', '0128_remove_stockitem_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Nome do setor ou departamento',
                        max_length=100,
                        unique=True,
                        verbose_name='Nome',
                    ),
                ),
                (
                    'code',
                    models.CharField(
                        blank=True,
                        help_text='Sigla ou código interno do setor',
                        max_length=25,
                        verbose_name='Sigla',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True, max_length=250, verbose_name='Descrição'
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=True,
                        help_text='Setores inativos não podem ser usados em novas movimentações',
                        verbose_name='Ativo',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'movement_type',
                    models.CharField(
                        choices=[
                            ('IN', 'Entrada'),
                            ('OUT', 'Saída'),
                            ('TRANSFER', 'Transferência'),
                            ('ADJUST', 'Ajuste'),
                        ],
                        db_index=True,
                        max_length=15,
                        verbose_name='Tipo',
                    ),
                ),
                (
                    'part_name',
                    models.CharField(
                        blank=True,
                        help_text='Nome do material no momento da movimentação',
                        max_length=250,
                        verbose_name='Material (descrição)',
                    ),
                ),
                (
                    'quantity',
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        max_digits=15,
                        verbose_name='Quantidade',
                    ),
                ),
                (
                    'quantity_before',
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        help_text='Saldo total do material antes da operação',
                        max_digits=15,
                        verbose_name='Saldo anterior',
                    ),
                ),
                (
                    'quantity_after',
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        help_text='Saldo total do material após a operação',
                        max_digits=15,
                        verbose_name='Saldo posterior',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        blank=True,
                        help_text='Origem do material (fornecedor, doação, devolução...)',
                        max_length=200,
                        verbose_name='Origem',
                    ),
                ),
                (
                    'requester',
                    models.CharField(
                        blank=True,
                        help_text='Pessoa que solicitou o material',
                        max_length=150,
                        verbose_name='Solicitante',
                    ),
                ),
                (
                    'handler',
                    models.CharField(
                        blank=True,
                        help_text='Pessoa que retirou ou recebeu fisicamente o material',
                        max_length=150,
                        verbose_name='Responsável',
                    ),
                ),
                (
                    'document',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Nota fiscal, protocolo ou documento de referência',
                        max_length=100,
                        verbose_name='Documento',
                    ),
                ),
                (
                    'reference_date',
                    models.DateField(
                        blank=True,
                        help_text='Data da nota fiscal ou protocolo (opcional)',
                        null=True,
                        verbose_name='Data do documento',
                    ),
                ),
                (
                    'notes',
                    models.CharField(
                        blank=True, max_length=512, verbose_name='Observações'
                    ),
                ),
                (
                    'date',
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name='Data'
                    ),
                ),
                (
                    'location_from',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements_out',
                        to='stock.stocklocation',
                        verbose_name='Local de origem',
                    ),
                ),
                (
                    'location_to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements_in',
                        to='stock.stocklocation',
                        verbose_name='Local de destino',
                    ),
                ),
                (
                    'part',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements',
                        to='part.part',
                        verbose_name='Material',
                    ),
                ),
                (
                    'sector',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='movements',
                        to='oab.sector',
                        verbose_name='Setor',
                    ),
                ),
                (
                    'supplier',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements',
                        to='company.company',
                        verbose_name='Fornecedor',
                    ),
                ),
                (
                    'tracking',
                    models.ForeignKey(
                        blank=True,
                        help_text='Entrada de histórico do InvenTree associada',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements',
                        to='stock.stockitemtracking',
                        verbose_name='Registro de auditoria',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Usuário do sistema que registrou a operação',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='oab_movements',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Registrado por',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-date', '-pk'],
            },
            bases=(
                InvenTree.models.ContentTypeMixin,
                InvenTree.models.PluginValidationMixin,
                models.Model,
            ),
        ),
    ]
