# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oab', '0001_initial'),
        ('stock', '0128_remove_stockitem_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHocLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oab_adhoc', to='stock.stocklocation', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Local avulso',
                'verbose_name_plural': 'Locais avulsos',
            },
        ),
    ]
