# Generated by Django 5.2.17 on 2026-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oab', '0002_adhoclocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data e hora'),
        ),
    ]
